CREATE TABLE IF NOT EXISTS roles (
  id   TINYINT UNSIGNED PRIMARY KEY,
  slug VARCHAR(30) NOT NULL UNIQUE,   -- 'admin', 'customer'
  name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
